services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "8080:5000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/spotify_festival_recommender
    volumes:
      - .:/app

  postgres:
    container_name: postgres-container
    image: postgres
    hostname: localhost
    # Port 6543 on the outside maps to 5432 inside
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: