services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "8080:5000"
    # depends_on:
    #   - database
    environment:
      DATABASE_URI: ${DATABASE_URI}
    volumes:
      - .:/app

  # database:
  #   container_name: postgres-container
  #   image: postgres
  #   hostname: db.ubesbxemvrevzeputnoo.supabase.co
  #   # External (host): Internal (container)
  #   ports:
  #     - "6543:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: SampliFiree
  #     POSTGRES_DB: postgres
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres-data: